# Common settings for the tool

etengine_url: https://engine.energytransitionmodel.com/api/v3

basic_scenario:
  end_year: 2050
  area_code: nl

kpis:
  - key: primary
    gquery: dashboard_energy_demand_primary_of_final
